=head1 NAME

URI::Encode::XS - a naive URI encoder/decoder using C

=head1 SYNOPSIS

  use URI::Encode::XS;

  my $encoded = URI::Encode::XS::uri_encode($data);
  my $decoded = URI::Encode::XS::uri_decode($encoded);

=head1 DESCRIPTION

This is a Perl module that wraps my naive C URI encoder/decoder based on
L<RFC3986|https://tools.ietf.org/html/rfc3986>.

It is significantly faster than URI::Escape at encoding and significantly
slower at decoding:

  $ perl bench
             Rate escape encode
  escape 191981/s     --   -81%
  encode 989400/s   415%     --
                Rate   decode unescape
  decode    865570/s       --     -73%
  unescape 3200383/s     270%       --

For a faster encoder/decoder which supports custom escape lists, check out
C<URI::XSEscape|https://metacpan.org/pod/URI::XSEscape>.

=head1 INSTALLATION

  $ git clone https://github.com/dnmfarrell/URI-Encode-XS
  $ cd URI-Encode-XS
  $ perl Makefile.PL
  $ make
  $ make test
  $ make install

=head1 LICENSE

See LICENSE

=head1 AUTHOR

E<copy> 2016 David Farrell

=cut
